### ISSUE TITLE
use fastaFileGenerator to speed up state generation in getStates()

### ISSUE THREAD

**Issue by philippmuench** [hiddengenome/deepG#25]
currently, `getStates()` from infer-states.R only works on a single GPU and cannot be used in a multip-GPU setting. we can add the fastaFileGenerator there (see `preprocess.R` which generates the junks needed for prediction).

**Comment by philippmuench** [comment]
best way would be to rename `fastaFileGenerator` to `fastaFolderGenerator` and add `fastaFileGenerator` which ends if end-of-file is reached

**Comment by mr-francois** [comment]
`predict_generator` is slightly faster than `predict_on_batch` (~90% run time) but would be problematic with other features:
1) For padding we would have to switch between  `predict_generator` and `predict_on_batch` 
2) Difficult to write states to h5 in batches while keeping track of current position in sequence
