### ISSUE TITLE
Benchmark if fasta generator is a bottleneck during training

### ISSUE THREAD

**Issue by philippmuench** [hiddengenome/deepG#61]
run training run with our generator, compare training time per batch with a dummy generator

**Comment by mr-francois** [comment]
The following call `trainNetwork(path = "/scratch/pmuench/representatives", 
               path.val = "/scratch/pmuench/representatives",
               use.cudnn = TRUE,
               use.codon.cnn = FALSE,
               maxlen = 128,
               batch.size = 512,
               run.name= "run", 
               epochs = 20, 
               steps.per.epoch = 1000,
               layers.lstm = 3, 
               max.queue.size = 250,
               dropout.rate = 0, 
               layer.size = 512,
               vocabulary.size = 6,
               dummyGen = TRUE)
  )` takes on average 282 seconds per epoche the same call with `dummyGen = FALSE ` takes 315 seconds per epoche.
