### ISSUE TITLE
Change size of validation set  

### ISSUE THREAD

**Issue by mr-francois** [hiddengenome/deepG#69]
Currently `trainNetwork` uses just one batch for validation per epoch

**Comment by philippmuench** [comment]
* depending how fast evaluation is, at least a few genomes should be processed for estimate the accuracy/loss on validation dataset best would be to use all genomes which is located in the folder for evaluation

* you here use the skip parameter to speed this up, if the evaluation takes to long for every position in the genome

**Comment by mr-francois** [comment]
Validation size is currently controlled by `validation.split`.
